name: legalrank

profile: legalrank

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  legalrank:
    +schema: raw
    +quote_columns: false

models:
  legalrank:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    mart:
      +materialized: table
flags:
  require_generic_test_arguments_property: true